### PR TITLE
Updated api URL and adapter settter

### PR DESCRIPTION
**Pull request by MauricioMoraes**

### CODE REVIEW

**Comment by dblock** [comment]
Happy to merge if you can fix the build & al.

**Comment by MauricioMoraes** [comment]
Hey @dblock. Thanks for reaching out!
 I've tried including the gem with the fixes from my branch, but it threw "symbol not found" errors for many known symbols. Some other fixes may be still needed and the errors must've been shadowed by that other error there. 

I'll try to fix the build! Thanks!

**Comment by dblock** [comment]
Are you actually able to use this? Google had deprecated the API/kept changing things, i've moved to IEX (https://github.com/dblock/iex-ruby-client).

**Comment by MauricioMoraes** [comment]
That may be the reason all symbols are failing. 😅

Thanks for pointing that out. I'll take a look at your other gem. 
Btw. Thanks for the terrific work on these gems.

**Pull request closed without merging**
